# Generated by Django 4.2.1 on 2023-05-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_employee_jobs_category_jobs_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='aboutus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='applicationmethod',
            field=models.TextField(null=True),
        ),
    ]
